# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cf6e75991e8a19534679467cfc851684a0abb5c74e79d2740bc925ec68d3bba93bd629158287b457f79bd2990971f04de33204f642bbaf672772c2b90fb8ed9

test:
  secret_key_base: 7ee59ca6c72b2e4820804fc4698b8d2200a2f1e17e677ba22dbb822bba28a764730261e7cc39362cfb34b840a0d8bc675ed38020225248234c50a7f1c9fa12f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
